# Generated by Django 5.0.3 on 2024-04-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Companies', 'verbose_name_plural': 'Companies'},
        ),
    ]
